/* FILE: BulkDMI6ngbr.h            -*-Mode: c++-*-
 *
 * Bulk Dzyaloshinskii-Moriya 6 neighbour energy derived from Oxs_Energy class.
 * Modification of Oxs_DMexchange6ngbr.h by Marijan Beg, Ryan A. Pepper, and Hans Fangohr (University of Southampton) January 2017
 */

#ifndef _OXS_BULKDMI6NGBR
#define _OXS_BULKDMI6NGBR

#include "atlas.h"
#include "key.h"
#include "energy.h"
#include "mesh.h"
#include "meshvalue.h"
#include "simstate.h"
#include "threevector.h"
#include "rectangularmesh.h"

class Oxs_BulkDMI6ngbr:public Oxs_Energy {
private:
  OC_INT4m A_size;
  OC_REAL8m** D;
  Oxs_Key<Oxs_Atlas> atlaskey;  
  Oxs_OwnedPointer<Oxs_Atlas> atlas;
  mutable OC_INT4m mesh_id;
  mutable Oxs_MeshValue<OC_INT4m> region_id;

protected:
  virtual void GetEnergy(const Oxs_SimState& state,
			 Oxs_EnergyData& oed) const;

public:
  virtual const char* ClassName() const; // ClassName() is
  /// automatically generated by the OXS_EXT_REGISTER macro.
  Oxs_BulkDMI6ngbr(const char* name,     // Child instance id
		   Oxs_Director* newdtr, // App director
		   const char* argstr);  // MIF input block parameters
  virtual ~Oxs_BulkDMI6ngbr();
  virtual OC_BOOL Init();
};


#endif // _OXS_BULKDMI6NGBR
